language: python
python:
  - 3.8
before_install:
  - sudo apt-get update
  - sudo apt-get install csound
  - wget https://lilypond.org/download/binaries/linux-64/lilypond-2.22.0-1.linux-64.sh
  - sh lilypond-2.22.0-1.linux-64.sh
install:
  - pip3 install .[testing]
  - pip3 install coveralls
script:
  - nosetests --with-coverage --cover-package=mutwo
after_success:
  - coveralls
