language: python
python:
  - 3.8
before_install:
  - sudo apt-get update
  - sudo apt-get install csound
  - sudo apt-get install lilypond
install:
  - pip3 install .[all]
  - pip3 install coveralls
script:
  - nosetests --with-coverage --cover-package=mutwo
after_success:
  - coveralls
