version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  build_test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get upgrade && sudo apt-get install csound && wget https://lilypond.org/download/binaries/linux-64/lilypond-2.22.0-1.linux-64.sh && sh lilypond-2.22.0-1.linux-64.sh --batch
      - run: pip3 install .[testing] && pip3 install coveralls
      - run:
          name: Run tests
          command: nosetests --with-coverage --cover-package=mutwo
  pypi_publish:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: |  # create whl, install twine and publish to PyPI
            pip3 install virtualenv
            virtualenv venv
            source venv/bin/activate
            pip3 install --upgrade pip
            pip3 install -U twine wheel setuptools
            python3 setup.py sdist bdist_wheel
            twine check dist/*
            twine upload dist/*
            deactivate

workflows:
  build_test_publish:
    jobs:
      - build_test
      - pypi_publish:
          requires:
            - build_test
          filters:
            branches:
              only:
                - main
