version: 2.1

orbs:
  python: circleci/python@1.2
  coveralls: coveralls/coveralls@1.0.6

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get upgrade && sudo apt-get install csound && wget https://lilypond.org/download/binaries/linux-64/lilypond-2.22.0-1.linux-64.sh && sh lilypond-2.22.0-1.linux-64.sh --batch
      - run: pip3 install .[testing] && pip3 install coveralls
      - run:
          name: Run tests
          command: nosetests --with-coverage --cover-package=mutwo
      - coveralls/upload
  pypi_publish:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: |  # create whl, install twine and publish to PyPI
            python setup.py sdist bdist_wheel
            sudo pip install pipenv
            pipenv install twine
            pipenv run twine upload dist/*

workflows:
  build_test_publish:
    jobs:
      - build-and-test
      - pypi_publish:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - main

