version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  sample:
    jobs:
      - build-and-test


jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run: sudo apt-get install csound && wget https://lilypond.org/download/binaries/linux-64/lilypond-2.22.0-1.linux-64.sh && sh lilypond-2.22.0-1.linux-64.sh --batch
      - run: pip3 install .[testing] && pip3 install coveralls
      - run:
          name: Run tests
          command: nosetests --with-coverage --cover-package=mutwo
